// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEGIEr2nyX4TtVr5TCc8ZXJtU5G9ZXYS0',
    appId: '1:183308785987:web:857dcb9e31eef8d0aeb7f6',
    messagingSenderId: '183308785987',
    projectId: 'demonotes-flutter-project',
    authDomain: 'demonotes-flutter-project.firebaseapp.com',
    storageBucket: 'demonotes-flutter-project.appspot.com',
    measurementId: 'G-M7VWX86XV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCGpCvjni1hMq30V0UJEppw4WmYqTQb4',
    appId: '1:183308785987:android:d4efcb35139e8670aeb7f6',
    messagingSenderId: '183308785987',
    projectId: 'demonotes-flutter-project',
    storageBucket: 'demonotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDsvbS0YCLVuvtH19QM3TRnNzlcqsd6ME',
    appId: '1:183308785987:ios:a5e2c570e8a70bd0aeb7f6',
    messagingSenderId: '183308785987',
    projectId: 'demonotes-flutter-project',
    storageBucket: 'demonotes-flutter-project.appspot.com',
    iosClientId: '183308785987-7ngc44epevslp5jcm038mlnsd6js8hjs.apps.googleusercontent.com',
    iosBundleId: 'com.psarmah.demonotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDsvbS0YCLVuvtH19QM3TRnNzlcqsd6ME',
    appId: '1:183308785987:ios:a5e2c570e8a70bd0aeb7f6',
    messagingSenderId: '183308785987',
    projectId: 'demonotes-flutter-project',
    storageBucket: 'demonotes-flutter-project.appspot.com',
    iosClientId: '183308785987-7ngc44epevslp5jcm038mlnsd6js8hjs.apps.googleusercontent.com',
    iosBundleId: 'com.psarmah.demonotes',
  );
}
